//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 02:55:49 PM BRT 
//


package org.jredfoot.utsli.glue.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 	    A host may have any of the properties of a subcluster.
 * 	
 * 	    TODO: really a Host shouldn't be allowed another Host below it? Can I
 * 	    specify a restriction in here to limit the number of subordinate Hosts
 * 	    to 0, or some trick like that?
 * 	  
 * 
 * <p>Java class for HostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mds.globus.org/glue/ce/1.1}SubClusterOrHostType">
 *       &lt;sequence>
 *         &lt;element name="ProcessorLoad" type="{http://mds.globus.org/glue/ce/1.1}LoadType" minOccurs="0"/>
 *         &lt;element name="SMPLoad" type="{http://mds.globus.org/glue/ce/1.1}LoadType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostType", propOrder = {
    "processorLoad",
    "smpLoad"
})
public class HostType
    extends SubClusterOrHostType
{

    @XmlElement(name = "ProcessorLoad")
    protected LoadType processorLoad;
    @XmlElement(name = "SMPLoad")
    protected LoadType smpLoad;

    /**
     * Gets the value of the processorLoad property.
     * 
     * @return
     *     possible object is
     *     {@link LoadType }
     *     
     */
    public LoadType getProcessorLoad() {
        return processorLoad;
    }

    /**
     * Sets the value of the processorLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadType }
     *     
     */
    public void setProcessorLoad(LoadType value) {
        this.processorLoad = value;
    }

    /**
     * Gets the value of the smpLoad property.
     * 
     * @return
     *     possible object is
     *     {@link LoadType }
     *     
     */
    public LoadType getSMPLoad() {
        return smpLoad;
    }

    /**
     * Sets the value of the smpLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadType }
     *     
     */
    public void setSMPLoad(LoadType value) {
        this.smpLoad = value;
    }

}
