//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 02:55:49 PM BRT 
//


package org.jredfoot.utsli.glue.base;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.globus.mds.glue.ce._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cluster_QNAME = new QName("http://mds.globus.org/glue/ce/1.1", "Cluster");
    private final static QName _GLUECESummary_QNAME = new QName("http://mds.globus.org/glue/ce/1.1", "GLUECESummary");
    private final static QName _GLUECE_QNAME = new QName("http://mds.globus.org/glue/ce/1.1", "GLUECE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.globus.mds.glue.ce._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link ProcessorType }
     * 
     */
    public ProcessorType createProcessorType() {
        return new ProcessorType();
    }

    /**
     * Create an instance of {@link RunTimeEnvironmentType }
     * 
     */
    public RunTimeEnvironmentType createRunTimeEnvironmentType() {
        return new RunTimeEnvironmentType();
    }

    /**
     * Create an instance of {@link SubClusterOrHostType }
     * 
     */
    public SubClusterOrHostType createSubClusterOrHostType() {
        return new SubClusterOrHostType();
    }

    /**
     * Create an instance of {@link GLUECERPType }
     * 
     */
    public GLUECERPType createGLUECERPType() {
        return new GLUECERPType();
    }

    /**
     * Create an instance of {@link FileSystemType }
     * 
     */
    public FileSystemType createFileSystemType() {
        return new FileSystemType();
    }

    /**
     * Create an instance of {@link ClusterType }
     * 
     */
    public ClusterType createClusterType() {
        return new ClusterType();
    }

    /**
     * Create an instance of {@link StorageDeviceType }
     * 
     */
    public StorageDeviceType createStorageDeviceType() {
        return new StorageDeviceType();
    }

    /**
     * Create an instance of {@link HostType }
     * 
     */
    public HostType createHostType() {
        return new HostType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link LoadType }
     * 
     */
    public LoadType createLoadType() {
        return new LoadType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link ComputingElementType }
     * 
     */
    public ComputingElementType createComputingElementType() {
        return new ComputingElementType();
    }

    /**
     * Create an instance of {@link NetworkAdapterType }
     * 
     */
    public NetworkAdapterType createNetworkAdapterType() {
        return new NetworkAdapterType();
    }

    /**
     * Create an instance of {@link RemoteFileSystemType }
     * 
     */
    public RemoteFileSystemType createRemoteFileSystemType() {
        return new RemoteFileSystemType();
    }

    /**
     * Create an instance of {@link ApplicationSoftwareType }
     * 
     */
    public ApplicationSoftwareType createApplicationSoftwareType() {
        return new ApplicationSoftwareType();
    }

    /**
     * Create an instance of {@link ArchitectureType }
     * 
     */
    public ArchitectureType createArchitectureType() {
        return new ArchitectureType();
    }

    /**
     * Create an instance of {@link SubClusterType }
     * 
     */
    public SubClusterType createSubClusterType() {
        return new SubClusterType();
    }

    /**
     * Create an instance of {@link AccessControlBaseType }
     * 
     */
    public AccessControlBaseType createAccessControlBaseType() {
        return new AccessControlBaseType();
    }

    /**
     * Create an instance of {@link DirectoryType.Mount }
     * 
     */
    public DirectoryType.Mount createDirectoryTypeMount() {
        return new DirectoryType.Mount();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link BenchmarkType }
     * 
     */
    public BenchmarkType createBenchmarkType() {
        return new BenchmarkType();
    }

    /**
     * Create an instance of {@link LocalFileSystemType }
     * 
     */
    public LocalFileSystemType createLocalFileSystemType() {
        return new LocalFileSystemType();
    }

    /**
     * Create an instance of {@link OperatingSystemType }
     * 
     */
    public OperatingSystemType createOperatingSystemType() {
        return new OperatingSystemType();
    }

    /**
     * Create an instance of {@link PolicyType }
     * 
     */
    public PolicyType createPolicyType() {
        return new PolicyType();
    }

    /**
     * Create an instance of {@link MainMemoryType }
     * 
     */
    public MainMemoryType createMainMemoryType() {
        return new MainMemoryType();
    }

    /**
     * Create an instance of {@link DirectoryType }
     * 
     */
    public DirectoryType createDirectoryType() {
        return new DirectoryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClusterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mds.globus.org/glue/ce/1.1", name = "Cluster")
    public JAXBElement<ClusterType> createCluster(ClusterType value) {
        return new JAXBElement<ClusterType>(_Cluster_QNAME, ClusterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GLUECERPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mds.globus.org/glue/ce/1.1", name = "GLUECESummary")
    public JAXBElement<GLUECERPType> createGLUECESummary(GLUECERPType value) {
        return new JAXBElement<GLUECERPType>(_GLUECESummary_QNAME, GLUECERPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GLUECERPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mds.globus.org/glue/ce/1.1", name = "GLUECE")
    public JAXBElement<GLUECERPType> createGLUECE(GLUECERPType value) {
        return new JAXBElement<GLUECERPType>(_GLUECE_QNAME, GLUECERPType.class, null, value);
    }

}
