//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 02:55:49 PM BRT 
//


package org.jredfoot.utsli.glue.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for PolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MaxWallClockTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MaxCPUTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MaxTotalJobs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MaxRunningJobs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyType", propOrder = {
    "any"
})
public class PolicyType {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "MaxWallClockTime", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer maxWallClockTime;
    @XmlAttribute(name = "MaxCPUTime", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer maxCPUTime;
    @XmlAttribute(name = "MaxTotalJobs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer maxTotalJobs;
    @XmlAttribute(name = "MaxRunningJobs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer maxRunningJobs;
    @XmlAttribute(name = "Priority", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer priority;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the maxWallClockTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxWallClockTime() {
        return maxWallClockTime;
    }

    /**
     * Sets the value of the maxWallClockTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxWallClockTime(Integer value) {
        this.maxWallClockTime = value;
    }

    /**
     * Gets the value of the maxCPUTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxCPUTime() {
        return maxCPUTime;
    }

    /**
     * Sets the value of the maxCPUTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxCPUTime(Integer value) {
        this.maxCPUTime = value;
    }

    /**
     * Gets the value of the maxTotalJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxTotalJobs() {
        return maxTotalJobs;
    }

    /**
     * Sets the value of the maxTotalJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxTotalJobs(Integer value) {
        this.maxTotalJobs = value;
    }

    /**
     * Gets the value of the maxRunningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxRunningJobs() {
        return maxRunningJobs;
    }

    /**
     * Sets the value of the maxRunningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxRunningJobs(Integer value) {
        this.maxRunningJobs = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
