//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 02:55:49 PM BRT 
//


package org.jredfoot.utsli.glue.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ProcessorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Vendor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ClockSpeed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="InstructionSet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OtherProcessorDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CacheL1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CacheL1I" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CacheL1D" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CacheL2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessorType", propOrder = {
    "any"
})
public class ProcessorType {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "Vendor", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String vendor;
    @XmlAttribute(name = "Model", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String model;
    @XmlAttribute(name = "Version", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String version;
    @XmlAttribute(name = "ClockSpeed", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer clockSpeed;
    @XmlAttribute(name = "InstructionSet", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String instructionSet;
    @XmlAttribute(name = "OtherProcessorDescription", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String otherProcessorDescription;
    @XmlAttribute(name = "CacheL1", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer cacheL1;
    @XmlAttribute(name = "CacheL1I", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer cacheL1I;
    @XmlAttribute(name = "CacheL1D", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer cacheL1D;
    @XmlAttribute(name = "CacheL2", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer cacheL2;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the clockSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClockSpeed() {
        return clockSpeed;
    }

    /**
     * Sets the value of the clockSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClockSpeed(Integer value) {
        this.clockSpeed = value;
    }

    /**
     * Gets the value of the instructionSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructionSet() {
        return instructionSet;
    }

    /**
     * Sets the value of the instructionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructionSet(String value) {
        this.instructionSet = value;
    }

    /**
     * Gets the value of the otherProcessorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherProcessorDescription() {
        return otherProcessorDescription;
    }

    /**
     * Sets the value of the otherProcessorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherProcessorDescription(String value) {
        this.otherProcessorDescription = value;
    }

    /**
     * Gets the value of the cacheL1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheL1() {
        return cacheL1;
    }

    /**
     * Sets the value of the cacheL1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheL1(Integer value) {
        this.cacheL1 = value;
    }

    /**
     * Gets the value of the cacheL1I property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheL1I() {
        return cacheL1I;
    }

    /**
     * Sets the value of the cacheL1I property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheL1I(Integer value) {
        this.cacheL1I = value;
    }

    /**
     * Gets the value of the cacheL1D property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheL1D() {
        return cacheL1D;
    }

    /**
     * Sets the value of the cacheL1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheL1D(Integer value) {
        this.cacheL1D = value;
    }

    /**
     * Gets the value of the cacheL2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheL2() {
        return cacheL2;
    }

    /**
     * Sets the value of the cacheL2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheL2(Integer value) {
        this.cacheL2 = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
