//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 02:55:49 PM BRT 
//


package org.jredfoot.utsli.glue.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for StateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TotalJobs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RunningJobs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="WaitingJobs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="WorstResponseTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="EstimatedResponseTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="FreeCPUs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateType", propOrder = {
    "any"
})
public class StateType {

    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "Status", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected String status;
    @XmlAttribute(name = "TotalJobs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer totalJobs;
    @XmlAttribute(name = "RunningJobs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer runningJobs;
    @XmlAttribute(name = "WaitingJobs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer waitingJobs;
    @XmlAttribute(name = "WorstResponseTime", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer worstResponseTime;
    @XmlAttribute(name = "EstimatedResponseTime", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer estimatedResponseTime;
    @XmlAttribute(name = "FreeCPUs", namespace = "http://mds.globus.org/glue/ce/1.1")
    protected Integer freeCPUs;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the totalJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalJobs() {
        return totalJobs;
    }

    /**
     * Sets the value of the totalJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalJobs(Integer value) {
        this.totalJobs = value;
    }

    /**
     * Gets the value of the runningJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRunningJobs() {
        return runningJobs;
    }

    /**
     * Sets the value of the runningJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRunningJobs(Integer value) {
        this.runningJobs = value;
    }

    /**
     * Gets the value of the waitingJobs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWaitingJobs() {
        return waitingJobs;
    }

    /**
     * Sets the value of the waitingJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWaitingJobs(Integer value) {
        this.waitingJobs = value;
    }

    /**
     * Gets the value of the worstResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWorstResponseTime() {
        return worstResponseTime;
    }

    /**
     * Sets the value of the worstResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWorstResponseTime(Integer value) {
        this.worstResponseTime = value;
    }

    /**
     * Gets the value of the estimatedResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEstimatedResponseTime() {
        return estimatedResponseTime;
    }

    /**
     * Sets the value of the estimatedResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEstimatedResponseTime(Integer value) {
        this.estimatedResponseTime = value;
    }

    /**
     * Gets the value of the freeCPUs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFreeCPUs() {
        return freeCPUs;
    }

    /**
     * Sets the value of the freeCPUs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFreeCPUs(Integer value) {
        this.freeCPUs = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
